name:  Continuous Build / Unit Test

on:
  push:
    paths-ignore:
    - documentation/**

env:
  rg:  gram-parser

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore
    - name: Install dependencies
      run: dotnet restore code
    # See https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build
    - name: Build
      run: dotnet build code --configuration Release --no-restore
    - name: Unit Tests
      run: |
        dotnet test code/KustoCopyTest --configuration Release \
          --no-build --verbosity normal
