name:  Test Infra

on:
  workflow_dispatch

env:
  rg:  ---

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Login
    - name: Azure Login
      run: az login --service-principal -u ${{ secrets.test_deploy_sp_id }} -p ${{ secrets.test_deploy_sp_secret }} --tenant ${{ secrets.test_tenant_id }}
    # Deploy
    - name: Deploy
      run: |
        cd deployment/integration-test
        bash deploy-integration-test-infra.sh ${{ secrets.test_rg }}
